import axios from 'axios';
import { req } from './axiosFun';
export const login = (params) => { return req("post", "/AdminUser/Login", params) };
export const BuildingEdit = (params) => { return req("post", "/Building/edit", params) };
export const BuildingDel = (params) => { return req("post", "/Building/del", params) };
export const BuildingList = (params) => { return req("post", "/Building/list", params) };
export const Buildingxllist = (params) => { return req("post", "/Building/xllist", params) };
export const HouseEdit = (params) => { return req("post", "/House/edit", params) };
export const HouseDel = (params) => { return req("post", "/House/del", params) };
export const HouseList = (params) => { return req("post", "/House/list", params) };
export const GarageEdit = (params) => { return req("post", "/Garage/edit", params) };
export const GarageDel = (params) => { return req("post", "/Garage/del", params) };
export const GarageList = (params) => { return req("post", "/Garage/list", params) };
export const Garagexllist = (params) => { return req("post", "/Garage/xllist", params) };
export const ParkingLotEdit = (params) => { return req("post", "/ParkingLot/edit", params) };
export const ParkingLotDel = (params) => { return req("post", "/ParkingLot/del", params) };
export const ParkingLotList = (params) => { return req("post", "/ParkingLot/list", params) };
export const StoreroomEdit = (params) => { return req("post", "/Storeroom/edit", params) };
export const StoreroomDel = (params) => { return req("post", "/Storeroom/del", params) };
export const StoreroomList = (params) => { return req("post", "/Storeroom/list", params) };
export const OwnerList = (params) => { return req("post", "/Owner/list", params) };
export const OwnerEdit = (params) => { return req("post", "/Owner/edit", params) };
export const OwnerByData = (params) => { return req("post", "/Owner/byData", params) };
export const OwnerMemberEdit = (params) => { return req("post", "/OwnerMember/edit", params) };
export const OwnerMemberByData = (params) => { return req("post", "/OwnerMember/byData", params) };
export const OwnerMemberList = (params) => { return req("post", "/OwnerMember/list", params) };
export const OwnerMemberUpdate = (params) => { return req("post", "/OwnerMember/update", params) };
export const OwnerMemberDel = (params) => { return req("post", "/OwnerMember/del", params) };
export const OwnerMemberUserList = (params) => { return req("post", "/OwnerMember/userList", params) };
export const CarouselList = (params) => { return req("post", "/Carousel/list", params) };
export const Carouseladd = (params) => { return req("post", "/Carousel/add", params) };
export const Carouseldel = (params) => { return req("post", "/Carousel/del", params) };
export const NoticeList = (params) => { return req("post", "/Notice/list", params) };
export const Noticeadd = (params) => { return req("post", "/Notice/add", params) };
export const Noticedel = (params) => { return req("post", "/Notice/del", params) };
export const DepartmentList = (params) => { return req("post", "/Department/list", params) };
export const DepartmentEdit= (params) => { return req("post", "/Department/edit", params) };
export const DepartmentDel = (params) => { return req("post", "/Department/del", params) };
export const DepartmentXlList = (params) => { return req("post", "/Department/xllist", params) };
export const AdminUserList = (params) => { return req("post", "/AdminUser/list", params) };
export const AdminUserEdit= (params) => { return req("post", "/AdminUser/edit", params) };
export const AdminUserDel = (params) => { return req("post", "/AdminUser/del", params) };
export const OwnerVehicleList = (params) => { return req("post", "/OwnerVehicle/list", params) };
export const OwnerVehicleEdit= (params) => { return req("post", "/OwnerVehicle/edit", params) };
export const OwnerVehicleDel = (params) => { return req("post", "/OwnerVehicle/del", params) };
export const OwnerVehicleAdminList = (params) => { return req("post", "/OwnerVehicle/adminList", params) };
export const RepairList = (params) => { return req("post", "/Repair/list", params) };
export const RepairLogEdit = (params) => { return req("post", "/RepairLog/edit", params) };
export const RepairLogList = (params) => { return req("post", "/RepairLog/list", params) };
export const InfoClassList = (params) => { return req("post", "/InfoClass/list", params) };
export const InfoClassEdit= (params) => { return req("post", "/InfoClass/edit", params) };
export const InfoClassDel = (params) => { return req("post", "/InfoClass/del", params) };
export const InfoClassxllist = (params) => { return req("post", "/InfoClass/xllist", params) };
export const InfoList = (params) => { return req("post", "/Info/list", params) };
export const Infoadd = (params) => { return req("post", "/Info/add", params) };
export const Infodel = (params) => { return req("post", "/Info/del", params) };
export const SeekHelpList = (params) => { return req("post", "/SeekHelp/list", params) };
export const SeekHelpAp = (params) => { return req("post", "/SeekHelp/ap", params) };
export const SuggestionList = (params) => { return req("post", "/Suggestion/list", params) };
export const SuggestionAp = (params) => { return req("post", "/Suggestion/ap", params) };
export const TelephoneList = (params) => { return req("post", "/Telephone/list", params) };
export const Telephoneadd = (params) => { return req("post", "/Telephone/add", params) };
export const Telephonedel = (params) => { return req("post", "/Telephone/del", params) };
export const ActivityList = (params) => { return req("post", "/Activity/list", params) };
export const Activityadd = (params) => { return req("post", "/Activity/add", params) };
export const Activitydel = (params) => { return req("post", "/Activity/del", params) };
export const ActivityUserList = (params) => { return req("post", "/ActivityUser/list", params) };
export const ActivityUserupdate = (params) => { return req("post", "/ActivityUser/update", params) };
export const OwnerVehicleAmountList = (params) => { return req("post", "/OwnerVehicleAmount/list", params) };
export const OwnerVehicleAmountEdit = (params) => { return req("post", "/OwnerVehicleAmount/edit", params) };
export const OwnerVehicleAmountdel = (params) => { return req("post", "/OwnerVehicleAmount/del", params) };
export const BasicByDate = (params) => { return req("post", "/Basic/byDate", params) };
export const BasicUpdate = (params) => { return req("post", "/Basic/update", params) };
export const BasicList = (params) => { return req("post", "/Basic/list", params) };
export const BasicAdd = (params) => { return req("post", "/Basic/add", params) };
export const BasicDel= (params) => { return req("post", "/Basic/del", params) };
export const Home= (params) => { return req("post", "/Home/home", params) };
export const BasicEdit= (params) => { return req("post", "/Basic/edit", params) };
export const QuestionnaireList = (params) => { return req("post", "/Questionnaire/list", params) };
export const Questionnaireadd = (params) => { return req("post", "/Questionnaire/add", params) };
export const Questionnairedel = (params) => { return req("post", "/Questionnaire/del", params) };
export const QuestionnaireTitleadd = (params) => { return req("post", "/QuestionnaireTitle/add", params) };
export const QuestionnaireTitlelist= (params) => { return req("post", "/QuestionnaireTitle/list", params) };
export const QuestionnaireTitledel = (params) => { return req("post", "/QuestionnaireTitle/del", params) };
export const QuestionnaireUserlist= (params) => { return req("post", "/QuestionnaireUser/list", params) };
export const HousexlList = (params) => { return req("post", "/House/xlList", params) };
export const BillEdit = (params) => { return req("post", "/Bill/edit", params) };
export const BillList = (params) => { return req("post", "/Bill/list", params) };
export const BillDel = (params) => { return req("post", "/Bill/del", params) };
export const BillJiao = (params) => { return req("post", "/Bill/jiao", params) };
export const ParkingLotxlList = (params) => { return req("post", "/ParkingLot/xlList", params) };
export const Billchelist = (params) => { return req("post", "/Bill/chelist", params) };
export const VolunteerList = (params) => { return req("post", "/Volunteer/list", params) };
export const VolunteerDel= (params) => { return req("post", "/Volunteer/del", params) };
export const shenhe= (params) => { return req("post", "/Volunteer/shenhe", params) };
export const ContributionList = (params) => { return req("post", "/Contribution/list", params) };
export const ContributionDel= (params) => { return req("post", "/Contribution/del", params) };
export const Contributionshenhe= (params) => { return req("post", "/Contribution/shenhe", params) };
export const MaterialList = (params) => { return req("post", "/Material/list", params) };
export const MaterialDel= (params) => { return req("post", "/Material/del", params) };
export const Materialshenhe= (params) => { return req("post", "/Material/shenhe", params) };
export const weiuserlist = (params) => { return req("post", "/AdminUser/weiuserlist", params) };


